## Using RMSE to Evaluate Model

In [2]:
import pandas as pd
import numpy as np

In [3]:
# loading 2019-20 projections
proj_df = pd.read_csv(r"C:\Users\15127\Springboard\Capstone2\nba-stats-csv\proj_2019.csv", header = 0)

In [5]:
proj_df.columns

Index(['Unnamed: 0', 'player_id', 'proj_season_id', 'proj_pts', 'proj_min',
       'proj_fgm', 'proj_fga', 'proj_fg3m', 'proj_fg3a', 'proj_ftm',
       'proj_fta', 'proj_oreb', 'proj_dreb', 'proj_ast', 'proj_stl',
       'proj_tov', 'proj_blk'],
      dtype='object')

In [6]:
# renaming columns to match with real_df
proj_df.rename(columns = {'proj_season_id':'season_id',
                               'proj_pts': 'pts',
                                'proj_min':'min',
                                'proj_fgm':'fgm',
                                'proj_fga':'fga',
                                'proj_fg3m':'fg3m',
                                'proj_fg3a':'fg3a',
                                'proj_ftm':'ftm',
                                'proj_fta':'fta',
                                'proj_oreb':'oreb',
                                'proj_dreb':'dreb',
                                'proj_ast':'ast',
                                'proj_stl':'stl',
                                'proj_tov':'tov',
                               'proj_blk':'blk'}, inplace = True)

In [7]:
proj_df = proj_df.dropna(how='all')
proj_df.drop('Unnamed: 0',axis = 1,inplace=True)
proj_df.reset_index(drop=True,inplace=True)

In [8]:
proj_df

,player_id,season_id,pts,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,ast,stl,tov,blk
0,203932,2019-20,12.310280,30.068440,4.883421,10.709664,0.971616,2.772954,1.601478,2.120597,1.245006,4.136951,2.786001,0.632545,1.290360,0.697544
1,1628988,2019-20,7.030954,16.866336,2.710971,6.097434,0.541188,1.579896,1.087308,1.321365,0.280215,1.377118,1.944523,0.442139,1.137575,0.118252
2,1627846,2019-20,5.807402,16.026917,2.199729,5.077327,0.827589,2.397080,0.581809,0.772578,0.507769,1.688650,0.730224,0.504290,0.592174,0.138781
3,201143,2019-20,10.723823,26.160810,4.286950,9.070040,0.928346,2.604569,1.241295,1.617945,1.258356,3.994569,2.750602,0.633547,1.398006,0.932645
4,202329,2019-20,8.774322,25.502777,3.321932,7.679073,1.059921,2.982736,1.148726,1.506686,1.379067,4.145796,1.299461,0.775207,1.160879,0.354087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,1627812,2019-20,5.904307,14.128193,2.315832,5.095075,0.465105,1.464927,0.805842,0.940558,0.201316,1.175653,1.652600,0.403390,0.838863,0.100379
458,1629139,2019-20,3.006193,9.004862,1.195864,2.584624,0.142921,0.435874,0.488352,0.679949,0.353990,1.097183,0.518359,0.304899,0.409699,0.162146
459,1628380,2019-20,8.845820,22.597974,3.473331,7.226017,0.437643,1.332901,1.455494,2.019040,1.440649,3.278591,1.201169,0.624825,0.871540,0.691822
460,203897,2019-20,20.799398,36.625176,7.528738,16.896277,1.649611,4.505406,4.133463,5.055562,1.023392,4.219291,4.036843,1.171746,2.442477,0.425483
461,2585,2019-20,4.070340,14.024158,1.472622,2.846675,0.000000,0.043023,1.135226,1.566584,1.406223,2.160599,0.495542,0.433155,0.726213,0.314868

In [21]:
# loading actual results of 2019-20 season
real_df = pd.read_csv(r"C:\Users\15127\Springboard\Capstone2\nba-stats-csv\NBA_Stats.csv", header = 0)

In [22]:
# cleaning...
real_df = real_df.dropna(how='all')
real_df.drop('Unnamed: 0',axis = 1,inplace=True)
real_df.reset_index(drop=True,inplace=True)

In [24]:
# isolating 2019-20 season
real_df = real_df[real_df['SEASON'] == '2019-20']

In [25]:
# aligning columns with proj_df
real_df = real_df[['PLAYER_ID','SEASON','PTS', 'GP','AGE','MIN','FGM','FGA','FG_PCT',
                   'FG3M','FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB','DREB',
                  'AST', 'TOV','STL','BLK']]

In [26]:
# matching names
real_df.columns = ['player_id','season_id','pts','gp','age','min','fgm','fga','fg_pct',
                   'fg3m','fg3a','fg3_pct','ftm','fta','ft_pct','oreb','dreb',
                   'ast', 'tov', 'stl','blk']

In [27]:
real_df.head()

,player_id,season_id,pts,gp,age,min,fgm,fga,fg_pct,fg3m,...,fg3_pct,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk
0,203932,2019-20,14.4,58,24.0,33.0,5.4,12.5,0.433,1.2,...,0.301,2.4,3.5,0.675,1.8,5.8,3.7,1.6,0.9,0.6
1,1628988,2019-20,9.4,58,23.0,23.6,3.5,8.6,0.407,1.4,...,0.394,1.1,1.2,0.861,0.4,1.9,3.3,1.3,0.8,0.2
2,1627846,2019-20,6.0,48,26.0,15.8,2.1,4.6,0.455,0.8,...,0.371,1.0,1.3,0.774,0.3,1.6,0.7,0.8,0.4,0.4
3,1629690,2019-20,2.9,11,21.0,10.2,1.1,2.5,0.429,0.5,...,0.400,0.2,0.4,0.500,0.6,0.3,0.4,0.2,0.4,0.0
4,1629678,2019-20,3.1,27,23.0,10.8,1.1,2.8,0.400,0.5,...,0.298,0.3,0.5,0.692,0.2,1.0,0.5,0.3,0.3,0.1

In [16]:
# merging data
merged = proj_df.merge(real_df,how='left',on=['player_id','season_id'])

In [46]:
# dropping any rows with NaN values
merged = merged.dropna(how='any')

In [31]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [47]:
# isolating real stats
real_df = merged.loc[:, ['pts_y','min_y','fgm_y','fga_y','fg3m_y','fg3a_y','ftm_y','fta_y','oreb_y','dreb_y','ast_y','stl_y','tov_y', 'blk_y']]

In [48]:
# isolating projected stats
proj_df = merged.loc[:, ['pts_x','min_x','fgm_x','fga_x','fg3m_x','fg3a_x','ftm_x','fta_x','oreb_x','dreb_x','ast_x','stl_x','tov_x', 'blk_x']]

In [49]:
real_df

,pts_y,min_y,fgm_y,fga_y,fg3m_y,fg3a_y,ftm_y,fta_y,oreb_y,dreb_y,ast_y,stl_y,tov_y,blk_y
0,14.4,33.0,5.4,12.5,1.2,3.9,2.4,3.5,1.8,5.8,3.7,0.9,1.6,0.6
1,9.4,23.6,3.5,8.6,1.4,3.5,1.1,1.2,0.4,1.9,3.3,0.8,1.3,0.2
2,6.0,15.8,2.1,4.6,0.8,2.2,1.0,1.3,0.3,1.6,0.7,0.4,0.8,0.4
3,12.0,30.8,4.8,10.9,1.5,4.4,0.9,1.2,1.5,5.3,4.1,0.9,1.1,0.9
4,4.3,21.1,1.4,4.8,0.5,2.0,1.1,1.6,1.3,3.5,1.2,1.0,0.9,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,5.9,21.0,2.1,5.2,1.1,3.5,0.6,0.7,0.3,3.8,1.1,0.5,1.0,0.3
457,4.2,11.0,1.5,3.8,0.4,1.6,0.7,0.8,0.1,1.0,1.3,0.3,0.6,0.1
458,1.9,6.2,0.8,1.8,0.2,0.5,0.2,0.5,0.4,0.7,0.3,0.3,0.1,0.1
459,9.0,28.8,3.0,6.3,1.0,2.3,2.0,2.0,1.3,2.7,2.0,0.0,2.0,0.7
460,25.5,34.8,9.0,20.0,3.1,8.1,4.5,5.6,0.7,4.1,4.2,1.5,3.4,0.5

In [50]:
proj_df

,pts_x,min_x,fgm_x,fga_x,fg3m_x,fg3a_x,ftm_x,fta_x,oreb_x,dreb_x,ast_x,stl_x,tov_x,blk_x
0,12.310280,30.068440,4.883421,10.709664,0.971616,2.772954,1.601478,2.120597,1.245006,4.136951,2.786001,0.632545,1.290360,0.697544
1,7.030954,16.866336,2.710971,6.097434,0.541188,1.579896,1.087308,1.321365,0.280215,1.377118,1.944523,0.442139,1.137575,0.118252
2,5.807402,16.026917,2.199729,5.077327,0.827589,2.397080,0.581809,0.772578,0.507769,1.688650,0.730224,0.504290,0.592174,0.138781
3,10.723823,26.160810,4.286950,9.070040,0.928346,2.604569,1.241295,1.617945,1.258356,3.994569,2.750602,0.633547,1.398006,0.932645
4,8.774322,25.502777,3.321932,7.679073,1.059921,2.982736,1.148726,1.506686,1.379067,4.145796,1.299461,0.775207,1.160879,0.354087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,6.406310,20.907596,2.499231,5.590710,0.620332,1.622130,0.801474,1.134365,1.320311,3.154271,1.445832,0.543590,0.983757,0.414988
457,5.904307,14.128193,2.315832,5.095075,0.465105,1.464927,0.805842,0.940558,0.201316,1.175653,1.652600,0.403390,0.838863,0.100379
458,3.006193,9.004862,1.195864,2.584624,0.142921,0.435874,0.488352,0.679949,0.353990,1.097183,0.518359,0.304899,0.409699,0.162146
459,8.845820,22.597974,3.473331,7.226017,0.437643,1.332901,1.455494,2.019040,1.440649,3.278591,1.201169,0.624825,0.871540,0.691822
460,20.799398,36.625176,7.528738,16.896277,1.649611,4.505406,4.133463,5.055562,1.023392,4.219291,4.036843,1.171746,2.442477,0.425483

In [51]:
# RMSE
se = mean_squared_error(real_df, proj_df)

In [52]:
# taking average
mse = np.mean(se)

In [53]:
# squaring
rmse = np.sqrt(mse)

In [54]:
confidence = rmse

In [55]:
print('{0} percent confidence in projected {1} per game stats'.format(100 - round(confidence, 2), '2019-20'))

97.86 percent confidence in projected 2019-20 per game stats